GalacticBundle\Entity\SectorType:
    type: entity
    table: sector_types
    repositoryClass: GalacticBundle\Repository\SectorTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        visibility:
            type: integer
        speed:
            type: integer
    lifecycleCallbacks: {  }
