# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        login:
            pattern: ^/
            anonymous: ~
            form_login:
                default_target_path: home
                login_path: login
                check_path: login
            provider: our_db_provider
        main:
            pattern:    ^/
            form_login:
                default_target_path: home
                login_path: login
                check_path: login
            provider: our_db_provider

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }