login:
    path:       /login
    defaults:   { _controller: AppBundle:Security:login }
    
register:
    path:       /register
    defaults:   { _controller: AppBundle:Security:register }
    
test:
    path:       /test
    defaults:   { _controller: AppBundle:Security:test }